### ISSUE TITLE
Linking to pthread and dl

### ISSUE THREAD

**Issue by donquichotte** [eduardo98m/RoboVis#1]
Hi, very cool project!

FYI, I needed to add `pthread` and `dl` to the CMakeLists.txt in the root directory to get it to build on Ubuntu 20.04.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 16a10c4..ae56ab1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -49,4 +49,4 @@ add_executable(SpringMassSimulation ${EXAMPLE_SOURCES} ${ROBO_VIS_SOURCES} ${IMG
 
 
 target_link_libraries(${PROJECT_NAME} PRIVATE raylib)
-target_link_libraries(SpringMassSimulation PRIVATE raylib)
\ No newline at end of file
+target_link_libraries(SpringMassSimulation PRIVATE raylib dl pthread)
\ No newline at end of file
```

**Comment by eduardo98m** [comment]
Thanks for raising this issue!

I am using Linux Mint 21.2 (Ubuntu 22.04 LTS).

I believe there may have been a mistake in the build instructions. Previously, when working on a similar project, I might have inadvertently installed an additional dependency for raylib/imgui, which could have automatically included `dl` and `pthread`.

I recall adding the following line to my `bash.rc`:

`export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH`

Upon checking the directory `/usr/lib/x86_64-linux-gnu`, I noticed that the libraries you mentioned are indeed present. This likely explains the issue.

I will update the README to include this information.

**Comment by eduardo98m** [comment]
I will close the issue as I updated the readme
